plugins {
    id 'java'
}

group = 'me.earth.plugingenerator'
version = '1.0'

repositories {
    mavenCentral()
}

configurations {
    compile
}

dependencies {
    compile 'com.formdev:flatlaf:3.3'

    configurations.compile.dependencies.each {
        implementation(it)
    }
}

jar {
    manifest {
        attributes(
            'Main-Class': 'me.earth.plugingenerator.Main'
        )
    }
    from {
        configurations.compile.collect { it.isDirectory() ? it : zipTree(it) }
    }
    exclude 'META-INF/'
    duplicatesStrategy(DuplicatesStrategy.EXCLUDE)
}